travis:
  secure:
    BINSTAR_TOKEN: sbY1ZPjPUb6PUFMCWJts8NRuxIt3jHqDYFyFW5VLGzbXKPao8FiqTeMPtZ4gRKiPU8uyiNoH3TzkcW3N22R3uatOHVdv7PxwuD37mQ1GUjrqsO5iSQpNi0Wzj+loRYQo3VjOulCI//or7zEQ9LCYvyslZ1mcVp9Ht7qg5tchDDtCUhX2cCo7gJoIiTLoc7zhmClkZUD42w+AcX2nGNAMTBmvY+Vl/h1rr2hPSUOMqCMgTxDFiWatk77BFRafmq8i7/OIP8rGruPz8fpXD6b5JmWk0+S69zSDFiiicPbjnUfjzszBEfnbvLo/U1+9KimNneETRa6aS6E0yi63XBAWwveo/2yV5lRWlf3znMw8YcDdKNr0810bIactTRCqKueSWv2r5Yf5NpO6BAlRYT/2tDdHHVsYerHaxeF1rswkroulVYfRfBR3Mi44ha+3HTMGUtl/1rw47EGkMxlVPZ3MQLZ2DERaO4doPr++FZeWwTAdbNxsBDiKyUtGD49/gWqgdBTWqTeinz7XY+97iQd38orm9bqTwKvTRCp5M8a6avGFuZxFMVWiRFh2Xc7FywtSohcxc0ZJeoHuGIjy6j10WGUsvBYlE0aVekcYAcgECJjyRpBngUxDvV2SBs6EK7KqPuDUvLuxQLV4PAgcuTISxl3K1oeDwPJ4KBgMKl+8lJI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
